name: Auto Restart Bot

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 */5 * * *" # Runs every 5 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Start the bot
      - name: Start Bot
        run: node index.js
